### PR TITLE
Formatting, error handling, and general cleanup

### PR DESCRIPTION
**Pull request by pattmax00**

### CODE REVIEW

**Comment by mrusme** [comment]
Thank you for the PR! Would you mind splitting it into three different ones -> "Error handling", "General cleanup" and "Formatting"? 

The formatting changes don't really matter that much and hinder actually reviewing the other changes. Also formatting is something that grew out of dislike for Go's way to dictate formatting, hence if you check the [`.editorconfig`](https://github.com/mrusme/superhighway84/blob/master/.editorconfig) you will find that it actually tells 2 spaces. I have given this up though as tooling has been increasingly difficult to *convince* to use two spaces and I'm slowly moving the code to Go's dictated tabs. I don't feel that it's worth making a whole PR about it though - especially not with other changes mixed in between.

**Comment by pattmax00** [comment]
Yes I can. To be clear though, you *are* okay with me doing formatting the way I have here? It's mostly `go fmt` stuff, the reason I include it as a separate commit in my PRs is because it's always just 1000+ lines of space changes and I don't want it to muddy future commits by myself or others since most editors just auto-format like what you were alluding to. I usually just do it first thing to avoid my commits getting obfuscated.

**Comment by mrusme** [comment]
Yeah, understood, hence I was saying that formatting changes aren't actually not important. So if you don't feel like doing it all over just don't, because it can be done successively. I also didn't see the need to go through each file and fmt just for the sake of it, as it would indeed pollute the history.

**Comment by pattmax00** [comment]
Yeah, I don't mind redoing anything. I'd probably just want to `go fmt` the whole project first because even now as I'm making small changes it's running `go fmt` automatically on individual files and screwing up my potential commits.

**Comment by mrusme** [comment]
Just disable your editor/IDE to run `go fmt` automatically and you should be good. If you're planning to contribute other things as well and this is truly blocking I can check this later and commit a reformat, but definitely not as individual commits as with this PR but rather a single big one.

**Pull request closed without merging**
