### PR TITLE
Add help and shortcuts reference view

### PR DESCRIPTION
**Pull request by mprimi**
Pressing '?' or 'z' displays a help modal.

Currently displays some placeholder text and shortcuts.
However the C- shortcuts are invisible characters.

Also does a little refactoring of the shortcuts.

### CODE REVIEW

**Comment by mprimi** [comment]
@mrusme  Do not merge, this is work in progress.

The thing works, but I need to clean up the PR.

**Comment by mprimi** [comment]
@mrusme one thing I don't know how to resolve, I wonder what you think:

If you try this branch, hitting '?' won't do anything. That's because:
 - You ran SH84 before on your machine
 - You have a config file somewhere
 - The config contains shortcut mappings, they're written out every time SH84 launches correctly
 - The default shortcuts (where I added '?' -> 'help') is only loaded if there are no shortcuts loaded from config!

So anyone that has a config file, will not have the help command mapped.

I see multiple ways out of this, but I wonder what you think.

**Comment by mrusme** [comment]
@mprimi yupp been having that exact issue with new shortcuts, hence the users would manually need to delete all shortcuts from the config in order to get the new ones. As you pointed out there are multiple ways to solve this issue, e.g. checking the ones that are there and only appending the new ones. I just haven't had the time to take care of implementing any of this yet.

If you feel like, go ahead and try something like that. I won't reject the PR if it doesn't take care of that though, as it's technically not part of what you're actually trying to solve here.

**Comment by mprimi** [comment]
@mrusme ready for review -- happy to make change if you don't like where state is created/composed/passed.

**Review by mrusme — APPROVED** [review]
Checked PR and tested locally, works! Lgtm

**Comment by mprimi** [comment]
@mrusme I see my PRs are creating merge commits.
I seem to remember you don't like them. Do you know you can set the PRs to merge as `--fast-forward` only?

(this means a PR may need to rebase before it can be merged, if HEAD moved, but that seems fair to ask)

**Pull request merged**
